#!/usr/bin/env bash

set -e

if [[ "$1" == "-d" ]]; then
  download=1
  shift
fi

if [[ "$1" =~ ^https://zenodo.org/record/.* ]]; then
    ID=$(echo "$1" | awk -F/ '{print $NF}')
elif [[ "$1" =~ ^https://doi.org/10.5281/zenodo.* ]]; then
    ID=$(echo "$1" | awk -F. '{print $NF}')
else
    ID="$1"
fi

if [[ ! "$ID" =~ ^[0-9]+$ ]]; then
    echo "Usage: $0 [-d] DOI|URL|ID"
    echo "Download all files from a publication at Zenodo.org. List files by default."
    echo "Option -d actually downloads, continuing partial downloads."
    exit 1
fi

curl -sL "https://zenodo.org/api/records/$ID" | jq -r '.files|map([.key,.links.self]|@tsv)[]' \
| while read file url; do
    if [[ -z "$download" ]]; then
        echo -e "$url\t$file"    
    else
        echo "$file"
        wget -cN "$url"
    fi
done 
